services:

  backend:
    image: localhost:8090/backend:latest
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studentdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "9090:9092"

  frontend:
    image: localhost:8090/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:8082"

  postgres:
    image: localhost:8090/postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
