    version: "3.8"
    services:
      registry:
        image: registry:latest
        ports:
          - "8090:5000"
        volumes:
          - registry-data:/var/lib/registry
    volumes:
      registry-data: